Entity folder
boppygames/Community-Game pull request #39
Opened 2021-07-11 13:11 UTC by johne5s

## All Submissions:

* [ ] I have read the LICENSE and agree to the terms for contributing Work.
* [ ] All 3rd party assets have been added to the `AssetManifest.list` and `.gitignore`
* [ ] All code submitted follows the [Coding Conventions](https://github.com/boppygames/community-game/wiki/coding-conventions)
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## New Feature

1. [ ] All new assets (including texture, scripts, etc) are within a `Features/<feature>` directory
2. [ ] Any new art assets match the level of detail expected in the game (assets should be low-poly)
3. [ ] Screenshots added if necessary

### Description of feature

Include a short description here of the feature or core change that you made

### Screenshots

Include a couple of screenshots or gifs here to show off the new feature. This is optional for features that don't have a visual component to them.

## Bug Fixes

1. [ ] Describe the issue that existed before this PR
2. [ ] The bug fix has been tested 
3. [ ] Optional: Screenshots for before/after the bug fix

2021-07-12 16:07 UTC, jdetter requested changes
This is great so far, I have a few feedback items that I think can improve the code. Let me know what you think, and thanks for the contributions :)

2021-07-13 00:40 UTC, johne5s commented on Assets/Features/Johne5/EnemyController.cs
> +// Copyright 2021 Boppy Games, LLC
everything in the johne5 folder should be removed.  I moved all the files to Assets/Features/Entity/

2021-07-13 00:45 UTC, johne5s commented on Assets/Features/Combat/Scripts/EntityHealthController.cs
> +  {
agree

2021-07-20 16:30 UTC, jdetter requested changes
One more small suggestion, other than that I'm ready to merge this :+1: 

Thanks @johne5s!

2021-07-20 16:30 UTC, jdetter commented on Assets/Features/Combat/Scripts/EntityHealthController.cs
> +    health = startingHealth;
Small suggestion: I think we should do a check at the top of this function
```C#
if (health > 0) return;
```

2021-07-31 17:19 UTC, jdetter approved these changes
My suggestions here were optional, lets merge this :)

2021-07-31 17:19 UTC, merged

2021-07-31 17:19 UTC, jdetter commented
Thanks for the contribution @johne5s!